package net.terullet.bibliothekarios.arachne.web.com.syosetu.api;

import javafx.util.Pair;
import net.terullet.bibliothekarios.arachne.RequestSource;
import net.terullet.bibliothekarios.arachne.RequestStatus;
import net.terullet.util.concurrent.NamedThreadFactory;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.io.InputStream;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Comparator;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;

public class NarouApiFetcher {
	private static final Logger logger = LogManager.getLogger(new Throwable().getStackTrace()[0].getClassName());
	private static volatile NarouApiFetcher instance;
	public static void initialize(HttpClient httpClient) {
		// ref.) https://mixi-inc.github.io/AndroidTraining/appendix/A.04.advanced-java.html#double-checked-locking
		if (instance == null) {
			synchronized (NarouApiFetcher.class) {
				if (instance == null) {
					if (httpClient == null) {
						throw new IllegalArgumentException("httpClient must not be null.");
					}
					instance = new NarouApiFetcher(httpClient);
				} else {
					throw new IllegalStateException("Already initialized by another thread.");
				}
			}
		} else {
			throw new IllegalStateException("Already initialized.");
		}
	}
	public static NarouApiFetcher getInstance() {
		if (instance == null) {
			throw new IllegalStateException("NarouFetcher is not initialized yet.");
		}
		return instance;
	}
	private NarouApiFetcher(HttpClient httpClient) {
		this.httpClient = httpClient;
	}

	private final HttpClient httpClient;

	public static final long DELAY = 2500L;
	private final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor(new NamedThreadFactory("NarouApiFetcher"));
	private ScheduledFuture<?> executorFuture;
	private final Queue<QueueItem> queue = new PriorityQueue<>(8, QueueItem.COMPARATOR);
	private final Object syncObj = new Object();
	private final AtomicLong queueIdGenerator = new AtomicLong(0L);

	private void execute() {
		QueueItem item;
		synchronized (this.syncObj) {
			// get item from queue.
			item = this.queue.poll();
			if (item == null) {
				// if queue is empty, then stop service.
				if (this.executorFuture != null) {
					this.executorFuture.cancel(false);
					this.executorFuture = null;
					logger.info("Stopped executor.");
				}
				return;
			}
		}

		// send request and back response.
		HttpResponse<InputStream> httpResponse;
		NarouApiQuery query = item.query();
		HttpRequest request = HttpRequest.newBuilder(query.getUri()).build();
		try {
			httpResponse = this.httpClient.send(request, HttpResponse.BodyHandlers.ofInputStream());
			logger.trace(httpResponse.headers());
			item.completableFuture().complete(new Pair<>(query, httpResponse.body()));
		} catch (IOException | InterruptedException e) {
			logger.warn(e);
			item.completableFuture().completeExceptionally(e);
		}
	}

	public CompletionStage<Pair<NarouApiQuery, InputStream>> fetch(NarouApiQuery query, RequestSource requestSource, RequestStatus requestStatus) {
		CompletableFuture<Pair<NarouApiQuery, InputStream>> completableFuture = new CompletableFuture<>();
		// add query to queue.
		synchronized (this.syncObj) {
			this.queue.offer(new QueueItem(this.queueIdGenerator.incrementAndGet(), query, requestSource, requestStatus, completableFuture));
			// activate executor if it is stopped.
			if (this.executorFuture == null || this.executorFuture.isDone()) {
				this.executorFuture = this.executor.scheduleAtFixedRate(this::execute, 0L, DELAY, TimeUnit.MILLISECONDS);
				logger.info("Activated executor.");
			}
		}
		return completableFuture;
	}

	/**
	 * API fetch queue item.
	 * @param queryId id generated by {@code NarouApiFetcher}.
	 * @param query query.
	 * @param requestSource who is the requester.
	 * @param requestStatus why is this request generated.
	 * @param completableFuture where to back response.
	 */
	private record QueueItem(long queryId, NarouApiQuery query, RequestSource requestSource, RequestStatus requestStatus, CompletableFuture<Pair<NarouApiQuery, InputStream>> completableFuture) {
		public static final Comparator<QueueItem> COMPARATOR = Comparator
				.comparing(QueueItem::requestSource)
				.thenComparing(QueueItem::requestStatus)
				.thenComparing(QueueItem::queryId);
	}
}
